### ISSUE TITLE
add images to @rocketseat/gatsby-theme-docs/src/text/index.mdx

### ISSUE THREAD

**Issue by eduardosanzbBCG** [Rocketseat/gatsby-themes#11]
Hi, is it's possible to add an image to the mdx file? It seems there is no configuration for it right?

**Comment by awconway** [comment]
In case it helps - I've just been setting up a site using this template today and it seems that adding an image to the static folder and just using normal markdown syntax for the image will work. Like this:

   ![image caption](./image.png)

**Comment by jpedroschmitz** [comment]
As @awconway have answered, simply add an image on the static folder and use it like normal markdown.

**Comment by SakifKhan98** [comment]
Can you please tell me how can I change the social sharing image in this template?

**Comment by jpedroschmitz** [comment]
Hey, you can change the default site image for social sharing under `gatsby-config.js`, on the option `siteImage`, that must reference an OG image inside the static folder from Gatsby. Check this ([documentation](https://rocketdocs.netlify.app/getting-started#example-usage)) if you need help.

Or, if you want to change an image for a specific document, [check this doc](https://rocketdocs.netlify.app/usage/creating-docs#example).
