### ISSUE TITLE
Problem on links inside documentation

### ISSUE THREAD

**Issue by mouradaouinat** [Rocketseat/gatsby-themes#13]
Description of issue

All links that redirect to GitHub are not working (the ones that have "Edit this page on GitHub"). The href is correct but gatsby is putting "https://sleepy-lichterman-8f6fee.netlify.app/" in front of every link, so we end up on a 404 page.

Browser Information
Browser: Chrome
Version: 80.0.3987.163 (Official Build) (64-bit)

Usage example
Enter the page: "https://sleepy-lichterman-8f6fee.netlify.app/getting-started" and click on "Edit this page on GitHub", you will be redirected to "https://sleepy-lichterman-8f6fee.netlify.app/github.com/izmjs/izmjs.github.io/tree/master/src/docs/getting-started.mdx"

**Comment by mouradaouinat** [comment]
Just a little help, I found what seems to be the problem;
![http](https://user-images.githubusercontent.com/34982954/83911890-feb40400-a764-11ea-838e-471fbc67ce75.png)

the problem is that the "githubEditUrl" prop is a string that starts with "http:/" and not "http://" so that's why the site considers it as internal route and not an external route

**Comment by jpedroschmitz** [comment]
Hey @mouradaouinat, sorry about the delay! Fixed it on #18!

To upgrade just run:

```
yarn add @rocketseat/gatsby-theme-docs@latest
```
