### ISSUE TITLE
Don't use @dontInfer on GraphQL type definitions

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [Rocketseat/gatsby-themes#17]
Hi there,
Thanks for the great theme! Since most of your users, probably going to be small sites, using `@dontInfer` on your GraphQL type definitions is an overkill. Specifically I need to add a field to MDX frontmatter, and type in `gatsby-theme-docs-core/gatsby-node.js` stops me from doing it. And since Gatsby can't overwrite `gatsby-node.js` my only option is to fork the theme.
Please resolve this issue. Thanks!

**Comment by jpedroschmitz** [comment]
Hey @Dragomir-Ivanov, thanks for pointing this out.

The issue was fixed on #18 🎉

**Comment by Dragomir-Ivanov** [comment]
Thanks a ton!
