### ISSUE TITLE
Prev/Next links don't honor sidebar.yml order

### ISSUE THREAD

**Issue by robmcguinness** [Rocketseat/gatsby-themes#2]
**Description of bug**

**Prev** and **Next** links appear to be in alphebetical order vs using the order of the `sidebar.yml`

**To Reproduce**

1. Go to https://rocketdocs.netlify.com/usage/creating-docs
2. Scroll down to to view **Prev** and **Next** links
4. Notice the page links 

**Expected behavior**

**Prev** is set to `Navigation` when it should be `Getting Started` and **Next** is set to `Getting Started` when it should be `Navigation`. The **Next** and **Prev** page links should use the order of `sidebar.yml`

**Screenshots**

![image](https://user-images.githubusercontent.com/281070/74304667-b2633500-4d2b-11ea-9e52-b2e3bb200292.png)

**Environment:**
**N/A**

**Additional context**

`---`

Apologies if I'm off the mark 🎉

**Comment by jpedroschmitz** [comment]
Hey @robmcguinness, thanks for opening this issue. We are aware of this problem and are planning to fix it on the next version of the project, that will be released in the next days 💜

Sorry for the inconvenience and keep rocking 🚀

**Comment by robmcguinness** [comment]
No worries! Thanks for great theme!

**Comment by jpedroschmitz** [comment]
Hey @jpvalery and @robmcguinness! I have already fixed this issue and I am going to release it as soon as I can. Thanks for your patience 💜

**Comment by JGeiser9** [comment]
Hey @jpedroschmitz I got the ordering working for this issue as well by fixing the core gatsby-node.js file but I noticed the prev/next doesn't respect the ordering of the sidebar.yml file. Do you have a way to force this to avoid alphabetized folders?

Happy to help out or submit a PR if needed.

Thanks for open sourcing a good docs project!

**Comment by jpedroschmitz** [comment]
Guys, I have released version `2.1.0`, that adds a table of content for pages, a button to edit page on GitHub and fixes the issue with prev/next links 🚀 

Also, I want to update the docs with more use cases and information. I would love suggestions or even PR's 😍If you have further questions or features request please create a new issue! For now, I am closing this. Thanks again for your patience and for using the theme 💜
