### ISSUE TITLE
Configurable default branch

### ISSUE THREAD

**Issue by jesseflorig** [Rocketseat/gatsby-themes#21]
**What would you like to be added**:

Add a field to the plugin config to modify the default branch.

**Why is this needed**:

Currently, the "Edit on GitHub" links point to `master` branch which might not exists.

**Is your enhancement request related to a problem? Please describe.**

Not all repos have a `master branch`

**Additional context**

I'm happy to make a PR for this.

**Comment by jpedroschmitz** [comment]
Hey @jesseflorig, it would be an awesome feature 🚀 

If you'd like to implement it, feel free to do so, just reply here confirming 💜

**Comment by jpedroschmitz** [comment]
Added the option to the latest version! 
To update it, just run `yarn add @rocketseat/gatsby-theme-docs@latest` and you're ready 🎉 

Closing it by now. Let me know if you have any issues 💜
