### ISSUE TITLE
How to use Gatsby Remark Plugins?

### ISSUE THREAD

**Issue by Hrishikesh-K** [Rocketseat/gatsby-themes#24]
## Summary

Hello. I'm trying to use a (few) Gatsby Remark Plugin(s) inside MDX. So, I followed this: https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/ and made my `gatsby-config.js` like this:

```
    plugins: [
      {
        resolve: `gatsby-remark-images`
      },
      {
        resolve: `gatsby-plugin-mdx`,
        options:
          {
            gatsbyRemarkPlugins: [
              {
                resolve: `gatsby-remark-images`,
                options:
                  {
                    maxWidth: 1280,
                    backgroundColor: `none`,
                    quality: 100,
                    disableBgImageOnAlpha: true,
                    disableBgImage: true
                  }
              }]
          }
      }]
  }
```

But, as soon as I run `gatsby develop`, I get:

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

unknown: Unexpected token (9:66)

  7 | export default function MDXContent(_ref) {
  8 |   var components = _ref.components,
> 9 |       props = _objectWithoutPropertiesLoose(_ref, ["components"]);
    |                                                                   ^C:/Users/Hrishikesh/Desktop/Portfolio/src/@rocketseat/gatsby-theme-docs/text/index.mdx: unknown: Unexpected token (9:66)

  7 | export default function MDXContent(_ref) {
  8 |   var components = _ref.components,
> 9 |       props = _objectWithoutPropertiesLoose(_ref, ["components"]);
    |                                                                   ^

File: src\@rocketseat\gatsby-theme-docs\text\index.mdx:9:66
```

The `index.mdx` file the error mentions is the one that came with the theme. It's unchanged. However, it gives the same error if I empty the file.

## Relevant information

This was just one remark plugin I was trying, but, I might need more later. So, I need to get this to work. Kindly help.

**Comment by jpedroschmitz** [comment]
Hey @Hrishikesh-K, this theme already includes `gatsby-plugin-mdx`, as you can [see here](https://github.com/Rocketseat/gatsby-themes/blob/master/%40rocketseat/gatsby-theme-docs-core/gatsby-config.js#L32-L51), maybe this is the reason the above error occurred. An option is adding a boolean to turn it off, something like `mdx: false`, so you can use your own MDX remark plugins without any issue. [Example](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-emilia-core/README.md#theme-options).

Let me know if you can address this enhancement, it would be awesome 💜

**Comment by Hrishikesh-K** [comment]
@jpedroschmitz So, as soon as I the notification, I began looking for ways to do it, as I'm not a great developer myself. Sadly, there's no clear way mentioned by anyone to do so, but, I'll keep looking. However, there are high chances you might end up doing that first.

**Comment by jpedroschmitz** [comment]
No problem, I'll take a look to ship it as soon as possible!

**Comment by jpedroschmitz** [comment]
Added the option to the latest version! 
To update it, just run `yarn add @rocketseat/gatsby-theme-docs@latest` and you're ready 🎉 

Closing it by now. Let me know if you have any issues 💜

**Comment by milgner** [comment]
I'm running into the same issue - I'd like configure some additional mdx plugins (mermaid.js) and have tried specifying `mdx: false` as an option for `gatsby-theme-docs` and adding my own `gatsby-plugin-mdx` section.
Regardless of whether I add it before or after the `@rocketseat/gatsby-theme-docs` block, I encounter the same issue as @Hrishikesh-K.

Do you have any tips on how to go about this?

Full plugins block:

```js
plugins: [
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.mdx`, `.md`],
        gatsbyRemarkPlugins: [
          `gatsby-remark-autolink-headers`,
          //`gatsby-remark-external-links`,
          `gatsby-remark-embedder`,
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 960,
              withWebp: true,
              linkImagesToOriginal: false,
            },
          },
          `gatsby-remark-responsive-iframe`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-mermaid`,
        ],
        plugins: [
          `gatsby-remark-autolink-headers`,
          //`gatsby-remark-external-links`,
          `gatsby-remark-images`,
          `gatsby-remark-mermaid`,
        ],
      },
    },
    {
      resolve: `@rocketseat/gatsby-theme-docs`,
      options: {
        configPath: `src/config`,
        docsPath: `src/docs`,
        repositoryUrl: `https://gitlab.com/r-eco/c.hub-2.0/documentation`,
        branch: "master",
        mdx: false, // we're rolling our own, see above
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Rocketseat Gatsby Themes`,
        short_name: `RS Gatsby Themes`,
        start_url: `/`,
        background_color: `#ffffff`,
        display: `standalone`,
        icon: `static/favicon.png`
      }
    },
    `gatsby-plugin-sitemap`,
    // {
    //   resolve: `gatsby-plugin-google-analytics`,
    //   options: {
    //     trackingId: `YOUR_ANALYTICS_ID`,
    //   },
    // },
    `gatsby-plugin-remove-trailing-slashes`,
    {
      resolve: `gatsby-plugin-canonical-urls`,
      options: {
        siteUrl: `https://rocketdocs.netlify.app`
      }
    },
    `gatsby-plugin-offline`
  ]
```
