### ISSUE TITLE
Top-left logo is unchangeable

### ISSUE THREAD

**Issue by vinayaksh42** [Rocketseat/gatsby-themes#26]
I am not sure if this is a thing i am unaware about or is it actually not present.

**What would you like to be added**:
Currently the top-left logo of Rocketseat is set by default and it is only possible to change it by changing the node module files of @rocketseat.
I think there should be a option to add that top-left logo from the config settings.

**Why is this needed**:
i faced this issue and i had to change the module files in order to change the top-left logo
this was the file i had to change: @rocketseat/gatsby-theme-docs/src/components/Logo.js

**Is your enhancement request related to a problem? Please describe.**
yes it is a problem while making a documentation using rocketseat, as everyone would most probably like to have their own logo at that position.

**Additional context**
the top-left logo
![screencapture-rocketdocs-netlify-app-2020-08-28-00_33_30](https://user-images.githubusercontent.com/54861487/91483981-1d3e1d00-e8c6-11ea-9b2a-24afb36e79a7.png)

**Comment by Hrishikesh-K** [comment]
@vinayaksh42 The docs (https://rocketdocs.netlify.app/usage/shadowing) clearly mention how it's supposed to be done. The short answer is Shadowing in Gatsby.

**Comment by vinayaksh42** [comment]
> @vinayaksh42 The docs (https://rocketdocs.netlify.app/usage/shadowing) clearly mention how it's supposed to be done. The short answer is Shadowing in Gatsby.

Thanks alot for the information. Will check it
