### ISSUE TITLE
How can I change this logo?

### ISSUE THREAD

**Issue by fatihyildizhan** [Rocketseat/gatsby-themes#3]
Hi,

I couldn't change the top image. How can I change this logo?

![left](https://user-images.githubusercontent.com/602600/75690155-6c0e4f80-5cb3-11ea-931e-d1e8b1ea27ac.png)

**Comment by jpedroschmitz** [comment]
Hey @fatihyildizhan, here on our shadowing tutorial we have an example:
https://rocketdocs.netlify.com/usage/shadowing

Let me know if it helped you 💜

**Comment by AlFalahTaieb** [comment]
I followed the shadowing documentation nothing is working :/

**Comment by bpmutter** [comment]
I have had the same problem. The solution in the docs does not seem to work.

**Comment by jeffersonnnn** [comment]
this tutorial doesn't work. can we get something working please?

**Comment by nemethricsi** [comment]
> Hey @fatihyildizhan, here on our shadowing tutorial we have an example:
> https://rocketdocs.netlify.com/usage/shadowing
> 
> Let me know if it helped you 💜

What if I want a `png`?

**Comment by nemethricsi** [comment]
@fatihyildizhan actually I could change it to a PDF logo like so:

in the `src/@rocketseat/gatsby-theme-docs/components` folder create a file called `Logo.js`

```jsx
import React from 'react';
import soupyLogo from '../images/soupy.png'

const Logo = () => <img src={soupyLogo} alt="soupy-logo" style={{ width: 160 }} />

export default Logo;
```

Works fine:

![Screenshot 2020-11-03 at 1 17 03](https://user-images.githubusercontent.com/35897699/97933206-5be2ce80-1d72-11eb-97b4-bca5281aab57.png)

**Comment by jpedroschmitz** [comment]
Glad it worked @nemethricsi, I'll make sure we have this use case covered on the docs!

**Comment by nemethricsi** [comment]
> Glad it worked @nemethricsi, I'll make sure we have this use case covered on the docs!

@jpedroschmitz Thank you João! I didn't expected that :D Anyways... little OFF: I'm really struggling with changing "Edit this page on GutHub" link to a Bitbucket link on the pages. Should I issue a feature request or something so...? Many thanks! ON

**Comment by jpedroschmitz** [comment]
Hey @nemethricsi, you can issue a feature request 💜

**Comment by karlsoderby** [comment]
Seems like running `gatsby clean` before starting the server will solve the issue of logo not changing.
