### ISSUE TITLE
How modify language?

### ISSUE THREAD

**Issue by felipesuri** [Rocketseat/gatsby-themes#35]
I want modify language.

For example, "On this page" I want modify for "Nesta página", "Next" I want modify for "Próximo documento", this is is possible?

If not possible, have a possibility that is add in a next future?

**Comment by notrab** [comment]
@felipesuri it doesn't seem possible (elegantly with shadowing at least) as `<h2>On this page</h2>` is part of the `TOC/index.js`. You could always shadow the entire `TOC/index.js` file, but I wouldn't recommend this.

It might be worth creating a separate component for the heading here so you can override the children to solve your issue, or it could be part of the theme config. What do you think @jpedroschmitz ?

**Comment by felipesuri** [comment]
Like now is not possible to update language, could be able to create a new component for edit the titles, for more languages ​​no only PT-BR.

(If have errors on language, please help me, I'm learning).

**Comment by jpedroschmitz** [comment]
Hey guys, so far it's not possible to change the language, only if you shadow all files, what I don't recommend.

I think it would be nice to have i18n, but we actually want to keep this theme simple.
