### ISSUE TITLE
Home page help

### ISSUE THREAD

**Issue by jeffersonnnn** [Rocketseat/gatsby-themes#37]
hey guys, I'm trying to create a page without the sidebar, basically a homepage for the docs site. any idea how I can work my way through that?

**Comment by notrab** [comment]
Hi @jeffersonnnn 

It's not a feature as such but you'd need to shadow the `src/components/Layout/index.js` file with your own implementation, and logic to conditionally show the sidebar.

I'd recommend not to shadow this file though, as it takes care of quite a bit of logic you wouldn't want outdated from the plugin source.

At a source plugin level... it may be worth breaking down `components/Layout` into smaller components that can be shadowed for easier composition.

**Comment by jeffersonnnn** [comment]
incredible. i'm a newbie at gatsby.js so this may take a fair amount of time to grapple with. any resources you recommend to make the curve a little less steeper?

**Comment by notrab** [comment]
You can "shadow" the homepage, and change the content as you require, as outlined in the theme docs.

The problem you have is that this page still contains the wrapping Layout component you can't escape (without drawbacks).

**Comment by jpedroschmitz** [comment]
Hey, I'll be closing this issue!

In case anyone has another solution or an example on how to do it, post here in the comments.

Thanks 💜
