### ISSUE TITLE
pragma and pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by reggaeman007jah** [Rocketseat/gatsby-themes#40]
I don;t think this has been reported previously

**Description of bug**
I am unable to open the basic starter for this. I receive the following errors:

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

C:\Users\ADMIN\Documents\A3C\PublicDocs\userguide\rocket-docs\node_modules\@rocketseat\gatsby-theme-docs\src\components\Docs\EditGithub.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | /* @jsx jsx */
    | ^
  2 | import React from 'react';
  3 | import { jsx, css } from '@emotion/core';
  4 | import PropTypes from 'prop-types';

File: node_modules\@rocketseat\gatsby-theme-docs\src\components\Docs\EditGithub.js

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

C:\Users\ADMIN\Documents\A3C\PublicDocs\userguide\rocket-docs\node_modules\@rocketseat\gatsby-theme-docs\src\components\Layout\index.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | /* @jsx jsx */
    | ^
  2 | import React, { useState, useRef } from 'react';
  3 | import { jsx, css } from '@emotion/core';
  4 | import PropTypes from 'prop-types';

File: node_modules\@rocketseat\gatsby-theme-docs\src\components\Layout\index.js

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

C:\Users\ADMIN\Documents\A3C\PublicDocs\userguide\rocket-docs\src\@rocketseat\gatsby-theme-docs\text\index.mdx: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import * as React from 'react'
    | ^
  2 |   /* @jsx mdx */
  3 | import { mdx } from '@mdx-js/react';
  4 | /* @jsx mdx */

File: src\@rocketseat\gatsby-theme-docs\text\index.mdx

failed Building development bundle - 10.201s

**To Reproduce**

**Expected behavior**

I would expect to be able to view the starter files in localhost:8000.

**Exception or Error**

The full error is shown above.

**Screenshots**

N/A

**Environment:**

**Additional context**

n/a

**Comment by jan-vaclavik** [comment]
+1 
I'm trying to use @rocketseat\gatsby-theme-docs in an existing create-react-library project and i have same problem with `gatsby develop`

**Comment by jan-vaclavik** [comment]
It looks like a bug in gatsby version 2.24.53.
I temporarily resolved the issue by changing the gatsby version to 2.24.51 in `package.json`.

`"gatsby": "^2.24.53" => "gatsby": "2.24.51"`

Source: https://github.com/gatsbyjs/gatsby/issues/26736

**Comment by reggaeman007jah** [comment]
Nice ... I will try that myself today :)

**Comment by fatihyildizhan** [comment]
You may use a lower react version until this issue resolve.

```
 "react": "16.13.1",
 "react-dom": "16.13.1"
```

**Comment by reggaeman007jah** [comment]
Hmm, thanks for the advice, but I am already on 16.13.1 ..

**Comment by reggaeman007jah** [comment]
> It looks like a bug in gatsby version 2.24.53.
> I temporarily resolved the issue by changing the gatsby version to 2.24.51 in `package.json`.
> 
> `"gatsby": "^2.24.53" => "gatsby": "2.24.51"`
> 
> Source: [gatsbyjs/gatsby#26736](https://github.com/gatsbyjs/gatsby/issues/26736)

Confirmed to work - thanks man :) :+1:

**Comment by jpedroschmitz** [comment]
Hey guys,

Fixed it on the latest version!

To upgrade, just run: `yarn add @rocketseat/gatsby-theme-docs@latest`.

I was waiting for the Emotion release that supports the new JSX transform 💜
