### ISSUE TITLE
How to shadow Header.js

### ISSUE THREAD

**Issue by sampow** [Rocketseat/gatsby-themes#43]
## Summary

Hello,
I'm trying to  shadow/override the gatsby-theme-docs theme. 
I need to override the header so i've created a Header.js under:
src > @rocketseat > gatsby-theme-docs > components > Header.js
and made some basic changes

But there is no override. Did i missed sometthing ?

## Relevant information

```
"@rocketseat/gatsby-theme-docs": "^2.2.3",
"gatsby": "^2.24.53",
"react": "^16.13.1",
```
<img width="1487" alt="Capture d’écran 2020-10-22 à 14 11 30" src="https://user-images.githubusercontent.com/8237797/96870064-a27e2200-1470-11eb-922f-5414eeba6268.png">

Thanks

**Comment by jpedroschmitz** [comment]
Hey @sampow, the header is shown just on mobile, have you checked it on a screen with less than `780px`?

**Comment by jpedroschmitz** [comment]
I'll close this issue. If you need more information, check #52.
