### ISSUE TITLE
Add Edit on Bitbucket button

### ISSUE THREAD

**Issue by nemethricsi** [Rocketseat/gatsby-themes#47]
**What would you like to be added**:

I would like to add an option for changing "Edit on GitHub" link for "Edit on Bitbucket".

**Why is this needed**:

I assume that Bitbucket is also very popular beside GitHub. For example at my company I've no choice we are using Bitbucket. 

**Is your enhancement request related to a problem? Please describe.**

The out of the box documentation template is wonderful but there is a "hard coded" Github link in the core modul.

**Additional context**

none

**Comment by jpedroschmitz** [comment]
Hey @nemethricsi, thanks for opening this issue 💜 

I think we should have support for GitLab too, and maybe a new config named `repositoryURL`, so users can place GitHub, BitBucket, or GitLab links. Based on that, the theme could generate edit links, just by checking the repository URL.

With this new option, we can depreciate `githubUrl` and keep it until a major version is released. 
New projects would use `repositoryUrl` by default.

**Comment by nemethricsi** [comment]
Thank you! Actually I'm pretty junior in webdev. I even tried to rewrite the core module by myself but since it's an "out-of-the-box template" it would be nice if it would have this option you just advised! 💜

**Comment by jpedroschmitz** [comment]
Quick update: I'll be working on other projects for the next weeks, but as soon as I can, I'll take a look at this.

In case anyone wants to code this feature, I'll be glad to accept a PR.

Thanks for the patience and understanding ❤️

**Comment by jpedroschmitz** [comment]
Hey, I have added the `repositoryUrl` option on the latest version. 
It supports GitHub, BitBucket, and GitLab repositories now!

To upgrade, just run `yarn add @rocketseat/gatsby-theme-docs@latest` and add the option on `gatsby-config`.

For BitBucket, don't add the `src/<branch>` on the link.
In case you need more information, check this [doc](https://rocketdocs.netlify.app/getting-started#theme-options).

If you need help, let me know 💜 
Thanks for your patience and feature request!
