### ISSUE TITLE
How to remove the ToC on the right side?

### ISSUE THREAD

**Issue by jpvalery** [Rocketseat/gatsby-themes#5]
Hi there,

Just updated to 2.1.0 and the ToC on the right isn't not to my taste. How can I get rid of it?

I tried shadowing `/src/@rocketseat/gatsby-theme-docs/components/Layout/index.js` by using the last version of the file that hadn't the ToC but it's not ideal as I have to shadow all the other files that are imported. And at this point, it's not really shadowing or gatsby-theme if I have to shadow all the files...

This should be available as an option to enable/disable in the options IMHO. Or be documented on how to easily remove it. 

Thanks!

**Comment by jpedroschmitz** [comment]
Hey @jpvalery, to get rid of the ToC you will need to add `disableTableOfContents: true` on your docs file. I am going to update the theme documentation to include this.

**Comment by jpvalery** [comment]
You mean in the front matter of the pages?

**Comment by jpedroschmitz** [comment]
Yes, on the frontmatter.

**Comment by jpvalery** [comment]
Thanks!
