### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by PatrickWitmer** [Rocketseat/gatsby-themes#51]
Hello,

First thank you for the starter.

My question is the 404 page doesn't seem to be working, if visit `/404` it's fine, but any other test just gives the server error page. Any help or am I just possibly missing something?

Thank you for your time.

**Comment by jpedroschmitz** [comment]
Hey @PatrickWitmer, could you create an example reproducing the error? It can be a repository or a CodeSandbox.

Testing with our [website](https://rocketdocs.netlify.app/fagasaf) (running the latest version of the theme), seems to be ok.

**Comment by PatrickWitmer** [comment]
I did some testing @jpedroschmitz, and it works on a test netlify deploy, but not my nginx cloud server.

[Here's a live example ](https://usuoondemand.millspub.com/asfd)

**Comment by jpedroschmitz** [comment]
Hum, sorry, but I don't have experience with Nginx.

If it's running ok on Netlify it's probably an error with your Ngnix config and not something with Gatsby or the theme.

**Comment by PatrickWitmer** [comment]
Do you think it could be a pathing issue with it being hosted on a subdomain?

**Comment by PatrickWitmer** [comment]
@jpedroschmitz I appreciate your time.
