### ISSUE TITLE
Is it possible to add custom header and footer to my website?

### ISSUE THREAD

**Issue by huanglvming** [Rocketseat/gatsby-themes#52]
i wanna add header and footer to my website, i wonder if it is possible to realize by using this frame? if yes, how?

thanks.

**Comment by jpedroschmitz** [comment]
Hey, the header is visible just on a screen with less than 780px.

As a Gatsby Theme, you can shadow and change all files, according to your needs. 

If you need a Footer, you can create one and add it to the [Layout](https://github.com/Rocketseat/gatsby-themes/blob/master/%40rocketseat/gatsby-theme-docs/src/components/Layout/index.js) or event at the [Docs file](https://github.com/Rocketseat/gatsby-themes/blob/master/%40rocketseat/gatsby-theme-docs/src/components/Docs/index.js).

If you don't know what shadowing is or have questions about it, [check this tutorial](https://www.gatsbyjs.com/docs/themes/shadowing/) from the Gatsby documentation.
