### ISSUE TITLE
Can I fit the web page to entire window ?

### ISSUE THREAD

**Issue by IMsumitkumar** [Rocketseat/gatsby-themes#54]
There is a lot of margin on the left and right side of the page. I don't want that extra unused space instead I want to fit the page to the entire window like in [rocketseat official website](https://react-native.rocketseat.dev/). Is it possible?

**Comment by jpedroschmitz** [comment]
Hey @IMsumitkumar, if you have found a solution for this problem, make sure to post it here 💜 
This way, if others want to do the same, they have an idea of how to get started.

---
About the problem:

To get started, you'll probably need to shadow the [Layout component](https://github.com/Rocketseat/gatsby-themes/blob/master/%40rocketseat/gatsby-theme-docs/src/components/Layout/styles.js) and update the Container `max-width` to a bigger value. We always recommend you to keep the standard values, but, if you want to change them, that's ok.
