### ISSUE TITLE
Request: Collapsible Sections 

### ISSUE THREAD

**Issue by chrislevinecentric** [Rocketseat/gatsby-themes#62]
Last request, would it be possible to add collapsible parent sections for example to the navbar, everything under Usage would be hidden until you click usage in which case it would then reveal the subsections/ pages?

**Comment by jpedroschmitz** [comment]
Hey @chrislevine-centricconsulting, we don't have any plans to add this feature to the theme, but I believe it will be easy to add it to your website by using something like the [`Disclosure`](https://reakit.io/docs/disclosure/) component from [Reakit](https://reakit.io/).

**Comment by jpedroschmitz** [comment]
I'll close this issue. If you have further questions, let me know in the comments 💜

**Comment by ilyanaDev** [comment]
@jpedroschmitz  I'd just like to say that this would be an awesome feature to include! I've been trying for the past couple days to implement it myself on a website using this theme, but without success. I'd love to see this feature in the future, and I'm sure there are many others who would as well. I'll try your suggestion from above in the meantime.
