### ISSUE TITLE
Add code splitting

### ISSUE THREAD

**Issue by alexgonch** [Rocketseat/gatsby-themes#81]
Currently, running Google PageSpeed Insights on https://rocketdocs.netlify.app/ gets a score of ~80/100 for mobile site and suggests removing unused JavaScript by lazy-loading the components not used in initial render. In React, simple code-splitting can be achieved with [React.lazy](https://reactjs.org/docs/code-splitting.html) function.

@jpedroschmitz would you be able to update the codebase or could you point me in the direction of the files I'd need to update myself so I can submit a PR?

**Comment by jpedroschmitz** [comment]
Hey @alexgonch, I can't look right now on this, but we have extensive guides on contributing to the project and developing themes for it. Take a look [at this file](https://github.com/Rocketseat/gatsby-themes/blob/main/.github/CONTRIBUTING.md), set up your machine, and inspect the code to see where we can improve and lazy load components to get better scores.

Let me know if you have any questions! As soon as I finish an update on another project, I can take a look here again.

**Comment by jpedroschmitz** [comment]
Closing this as stale
