### ISSUE TITLE
This theme needs a search function.

### ISSUE THREAD

**Issue by hibbb** [Rocketseat/gatsby-themes#88]
I think this theme need a search function.

Or Is there an appropriate plugin to support search function?

**Comment by jpedroschmitz** [comment]
Hey @hibbb, thanks a lot for this suggestion.

We have already considered adding search to the theme, but we don't have plans to support it anymore, as mentioned on our [docs](https://rocketdocs.netlify.app/faq). For more info, please check [#16](https://github.com/Rocketseat/gatsby-themes/issues/16#issuecomment-758985415) and #61.

As alternatives, you can shadow the theme and implement it. I recommend using [Algolia DocSearch](https://docsearch.algolia.com/).
