### ISSUE TITLE
Populate TOC with html and Full markdown support

### ISSUE THREAD

**Issue by robertveloso** [Rocketseat/gatsby-themes#9]
**What would you like to be added**:

Populate TOC with <h1, h2> instead of just ##. Also, if possible, allow a nested ordered list

Add Emphasis Markdown features others features are working.
https://guides.github.com/features/mastering-markdown/

**Why is this needed**:

Styled title with the style prop in header tags <h1, h2>

**Additional context**

![Screenshot 2020-04-09 at 15 32 45](https://user-images.githubusercontent.com/31905169/78928753-889e6400-7a77-11ea-840e-f37f02d5d8a3.png)
![Screenshot 2020-04-09 at 15 33 25](https://user-images.githubusercontent.com/31905169/78928758-89cf9100-7a77-11ea-82c0-61e4648a27de.png)

Thanks in advance!

**Comment by jpedroschmitz** [comment]
I have tested it out and for some weird reason, this only happens while in development. 
If you build your website it will add all the HTML elements from MDX on the table of contents.

I don't know if this a problem with MDX or with the theme.

In case anyone knows how to fix it, I'll certainly accept your PR 💜

**Comment by jpedroschmitz** [comment]
Hey, I've been searching for this problem and doesn't found a solution. But, at least when running the build, it works ok and the TOC is populated with the HTML heading tags. In case anyone knows how to fix this problem that occurs during development, I'll be glad to reopen this issue and accept a PR!

Thanks for your patience and understanding 💜
