### ISSUE TITLE
Styling when using basePath

### ISSUE THREAD

**Issue by errrken** [Rocketseat/gatsby-themes#94]
First, Thanks for a great theme.

If I use this theme on a existing site, and use the basePath: '/docs' - the styling of the theme is also applied to our main page using Tailwind CSS. Any idea how I can change this behaviour?

Thanks

**Comment by jpedroschmitz** [comment]
That's weird. Could you create a minimal reproduction example so I can check it?

**Comment by jpedroschmitz** [comment]
Closing it for now. Glad to reopen if an example is provided.
