### ISSUE TITLE
Support for FeaturedImage / OpenGraph Image per Page?

### ISSUE THREAD

**Issue by ardalis** [Rocketseat/gatsby-themes#97]
## Summary

I'd like each page in my docs site to have its own <meta og:image /> image for preview links. Currently they all just show the site banner.png. How would I add this functionality, or is there a plan to update this template to support it?

In another Gatsby theme I'm suing for my blog, there is a featureimage: /img/whatever.png in the frontmatter that is used for this purpose. Could we do the same here?

My docs site: deviq.com
My blog site: ardalis.com

**Comment by jpedroschmitz** [comment]
Hey! We already support it. Take look at our docs, we have this covered.

https://rocketdocs.netlify.app/usage/creating-docs

You can add an `image` field in the frontmatter. That'll be used for the Open Graph image. Always relative to the `static` folder.
